export type {
  Integer,
  Negative,
  NegativeInteger,
  NonNegative,
  NonNegativeInteger,
  NonPositive,
  NonPositiveInteger,
  NonZero,
  NonZeroInteger,
  Positive,
  PositiveInteger,
  IntegerFamily,
} from './specificNumbers';
export {
  integer,
  negative,
  negativeInteger,
  nonNegative,
  nonNegativeInteger,
  nonPositive,
  nonPositiveInteger,
  nonZero,
  nonZeroInteger,
  positive,
  positiveInteger,
  isInteger,
  isNegative,
  isNegativeInteger,
  isNonNegative,
  isNonNegativeInteger,
  isNonPositive,
  isNonPositiveInteger,
  isNonZero,
  isNonZeroInteger,
  isPositive,
  isPositiveInteger,
} from './specificNumbers';
